- name: Add nfs-common package
  package:
    name: nfs-common
    state: present
- name: Add longhorn Helm repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
  tags:
    - longhorn
- name: Install/Upgrade Longhorn
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: "{{ longhorn_chart_version }}"
    namespace: longhorn-system
    create_namespace: true
    values:
      ingress:
        enabled: true
        ingressClassName: nginx
        host: "{{ longhorn_hostname }}"
        tls: true
        tlsSecret: longhorn-rancher-tls
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: true
          cert-manager.io/cluster-issuer: "{{ certmanager_cluster_issuer_name }}"
      defaultSettings:
        defaultDataPath: /data/longhorn
    wait: true
    wait_timeout: 600s
  tags:
    - longhorn
