---
# tasks file for rancher-on-k3s
- import_tasks: cert-manager.yaml
  tags:
    - cert-manager
- import_tasks: ingress-nginx.yaml
  tags:
    - ingress-nginx
- import_tasks: rancher.yaml
  tags:
    - rancher
- import_tasks: longhorn.yaml
  tags:
    - longhorn
- import_tasks: minio.yaml
  tags:
    - minio
- import_tasks: postgres-operator.yaml
  tags:
    - postgres-operator
